services:
  searchproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: searchproxy
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./data:/data
